const API_HOST = process.env.REACT_APP_API_URL;
const TWITCH_APIKEY = process.env.REACT_APP_TWITCH_APIKEY;
const YOUTUBE_APIKEY = process.env.REACT_APP_YOUTUBE_APIKEY;
const WEATHER_APIKEY = process.env.REACT_APP_WEATHER_APIKEY;
const CINEMA_APIKEY = process.env.REACT_APP_CINEMA_APIKEY;

export {
  API_HOST,
  TWITCH_APIKEY,
  YOUTUBE_APIKEY,
  WEATHER_APIKEY,
  CINEMA_APIKEY
};
